
networks:
  app:
    external: true
    name: "flux-network"

services:
  uart:
    image: uart-lidar
    build:
      context: .
      dockerfile: ./uart/Dockerfile
    privileged: true
    environment:
      MQTT_BROKER: "mqtt://mqtt-broker:1883"
      LOG_LEVEL: "debug"
      CONFIGURATION: |
        {
          "serial_port":  "/dev/ttyTHS0",
          "baud_rate": 115000,
          "read_interval_secs": 0.01,
          "distance_min_cm":  0,
          "frequdistance_max_cm": 10000,
          "topic": "neurons/test-steering/out"
        }
    networks:
      app:

#  forward:
#    image: forward-control
#    build:
#      context: .
#      dockerfile: ./forward/Dockerfile
#    privileged: true
#    environment:
#      MQTT_BROKER: "mqtt://mqtt-broker:1883"
#      CONFIGURATION: |
#        {
#          "full_forward":  55,
#          "full_backward": 40,
#          "full_stop": 53,
#          "pin":  32,
#          "frequency": 400,
#          "topic": "neurons/test-forward/out"
#        }
#    networks:
#      app:
